name: CI Pipeline
 
on: push

jobs: 
    project-testing:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup python
            uses: actions/setup-python@v4
            with:
              python-version: '3.13.7'

          - name: Install dependencies
            run: |
              python pip install --upgrade pip
              pip install -r requirements.txt
              pip install dvc

          - name: Run DVC pipeline
            run: |
              # directly run the DVC pipeline without pulling
              dvc repro
              