name: CI Pipeline
 
on: push

jobs: 
    project-testing:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup python
            uses: actions/setup-python@v4
            with:
              python-version: '3.13.7'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install dvc

          - name: Run DVC pipeline
            env:
              DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
            run: |
              # Directly run the DVC pipeline without pulling
              dvc repro

          - name: Run model tests
            env:
             DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
            run: |
             python -m unittest tests/model_test.py

          # Log in to DockerHub
          - name: Log in to DockerHub
            uses: docker/login-action@v2
            with:
              username: ${{secrets.DOCKER_USERNAME}}
              password: ${{secrets.DOCKER_TOKEN}}

          # Build the Docker Image
          - name: Build Docker Image
            if: ${{success()}}
            run: |
              docker build -t isaacotom/water-potability-predictor:latest .

          # Push the Docker Image only if the build step was successful
          - name: Push Docker Image
            if: ${{success()}}
            run: |
              docker push isaacotom/water-potability-predictor:latest
